import {Inter, Caveat} from 'next/font/google';
import './globals.css';
import './output.css';
import './styles.scss';
import Header from '../components/header'
import Footer from '../components/footer';
import Modal from "@/components/modal";
import {ModalProvider} from "@/components/modalcontext";

const interSans = Inter({
    variable: '--font-inter-sans',
    subsets: ['latin'],
});

const caveatSans = Caveat({
    variable: '--font-caveat-sans',
    subsets: ['latin'],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={`${interSans.variable} ${caveatSans.variable} antialiased`}>
        <ModalProvider>
            <Header />
            <main>{children}</main>
            <Footer />
            <Modal /> {/* Добавляем модалку, чтобы она была доступна везде */}
        </ModalProvider>
        </body>
        </html>
    );
}
